Update fwifi

diff --git a/src/fwifi b/src/fwifi
--- a/src/fwifi
+++ b/src/fwifi
@@ -65,6 +65,13 @@ if [[ $handshakes -gt 0 ]]; then
     read -p "Do you want to use the default wordlist (rockyou.txt)? [Y/n] " use_default_wordlist
     if [[ $use_default_wordlist == "n" || $use_default_wordlist == "N" ]]; then
         read -p "Enter the name of the custom wordlist: " custom_wordlist
+        if [[ -z "$custom_wordlist" ]]; then
+            echo "Custom wordlist cannot be empty."
+            exit 1
+        elif [ ! -f "$custom_wordlist" ]; then
+            echo "Custom wordlist '$custom_wordlist' not found."
+            exit 1
+        fi
         wordlist_option="-w $custom_wordlist"
     else
         wordlist_option="-w wordlists/rockyou.txt"
